name: wasm wast spec

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Synchronize Submodules
        run: git submodule sync --recursive

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Verify Submodule Status
        run: git submodule status

      - name: Install wasm-tools 1.221.2
        run: |
          wget https://github.com/bytecodealliance/wasm-tools/releases/download/v1.221.2/wasm-tools-1.221.2-x86_64-linux.tar.gz -O wasm-tools.tar.gz
          mkdir wasm-tools
          tar -xzf wasm-tools.tar.gz -C wasm-tools --strip-components=1
          sudo cp wasm-tools/wasm-tools /usr/local/bin/

      - name: Verify wasm-tools Installation
        run: wasm-tools --version

      - name: Run build_tests.sh script
        working-directory: ./Spec.Test
        run: |
          chmod +x build_spec_tests.sh
          ./build_spec_tests.sh

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal Spec.Test/Spec.Test.csproj